accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from accounts.views import signup


urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

projects/urls.py
from django.urls import path
from projects.views import ProjectListView, ProjectDetailView

urlpatterns = [
    path("", ProjectListView.as_view(), name="list_projects"),
    path("<int:pk>/", ProjectDetailView.as_view(), name="show_project"),
   
]

tracker/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from accounts.views import signup


urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("list_projects")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("accounts/signup/", signup, name="signup"),
]

accounts/models.py
from django.db import models

# Create your models here.

projects/models.py
from django.db import models
from django.conf import settings


class Project(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=None)
    members = models.ManyToManyField(
        settings.AUTH_USER_MODEL, related_name="projects"
    )

    def __str__(self):
        return self.name

tasks/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
from projects.models import Project


# Create your models here.
class Task(models.Model):
    name = models.CharField(max_length=200)
    start_date = models.DateTimeField(auto_now_add=False)
    due_date = models.DateTimeField(auto_now=False)
    is_completed = models.BooleanField(default=True)
    project = models.ForeignKey(
        Project, related_name="tasks", on_delete=models.CASCADE
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        related_name="tasks",
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = authenticate(
                request,
                username=username,
                password=password,
            )
            if user is not None:
                login(request, user)
                return redirect("home")
            return render(request, "registration/signup.html", {})

projects/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from projects.models import Project
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy


# Create your views here.


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = "projects/list.html"
    fields = ["name", "author", "description", "image"]
    success_url = reverse_lazy("accounts_list")


def get_queryset(self):
    return self.model.objects.filter(members=self.request.user)


class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = "projects/detail.html"
    login_url = '/login/'
    redirect_field_name = 'redirect_to'
  

tasks/views.py
from django.shortcuts import render

# Create your views here.

projects/templates/base.html
<!-- {% load static %} -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- <link rel="stylesheet" href="{% static 'css/app.css' %}"> -->
    <title>Me Receipts</title>
</head>

<body>
    <header>
        <nav>
            <ul class="navigation">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'home' %}">Home</a>
                </li>
    
                <!-- </li>
                <li class="nav-item">
                    <a href="{% url 'create_receipt' %}">Create receipt</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'list_accounts' %}">Accounts</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create_account' %}">Create account</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'list_categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'create_category' %}">Create category</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'logout' %}">Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                </li> -->
                <li class="nav-item">
                    <a href="{% url 'login' %}">Login</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </header>
    {% block content %}
    {% endblock content %}

</body>

</html>

projects/templates/projects/detail.html
{% extends 'base.html' %}


{% block title %}
{% endblock %}

{% block content %}


<h1>{{ project.name }}</h1>
<h2>{{ project.tasks" }}</h2>
<p>
    Created on {{ project.created }} |
    Updated on {{ project.updated }}
</p>
{% if <project class="tasks"></project> %}

<h2>Tasks</h2>
{% if project_list %}
<div>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Assignee</th>
                <th>Start date</th>
                <th>Due date</th>
                <th>Is completed</th>
            </tr>
        </thead>
        <tbody>
            {% for project in project_list %}
            <tr>
                <td>{{ project.name }}</td>
                <td>{{ project.number }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
    <p>The project has no tasks</p>

    {% endif%}
</div>
</main>
{% endblock content %}

projects/templates/projects/list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>

    {% block title %}

    {% endblock %}

    {% block content %}
    <main>
        <div>
            <h1>My Projects</h1>

            {% if project_list %}
            <table>
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>Number of tasks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for project in project_list %}
                    <a href="{% url 'detail.hmtl' projects.pk %}"></a>
                    <tr>
                        <td>{{ project.name }}</td>
                        <td>{{ project.number }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
            {% else %}
            <p>You are not assigned to any projects</p>

            {% endif%}
        </div>

    </main>

    {% endblock %}